### ISSUE TITLE
Menu pour afficher les games (triage? ...) et bouton pour enregistrer une game à sa fin

### ISSUE THREAD

**Issue by ThiraNoe** [lj44-ch/kart-simulator#61]

**Comment by lj44-ch** [comment]
# API du serveur faite!

## Get /games/kart/mygames.json
Retourne la liste des meilleures parties. Une parties est considérée meilleures lorsque le temps est plus petit (du moment que le joueur n'a pas brûlé!)

Variables (optionnelles):
- worldVersion_id
- world_id
- maxGame
- minPlayers
- maxPlayers

## Get /games/kart/bestgames.json
Retourne les parties du joueur, trié par date.

Variables (optionnelles):
- worldVersion_id
- world_id
- maxGame
- minPlayers
- maxPlayers

**Comment by ThiraNoe** [comment]
Fait sans le bouton: tout enregistré
