### ISSUE TITLE
Une méthode côté serveur qui informe les clients à chaque fois qu'un nouveau joueur join la partie.

### ISSUE THREAD

**Issue by ThiraNoe** [lj44-ch/kart-simulator#84]
Pour l'ajouter à la liste des joueurs de la waiting room.
Il faut donc appeler les méthodes on_new_connection ou on_new_disconnection

**Comment by lj44-ch** [comment]
Il y a déjà un game_data event qui est émis à chaque connexion et déconnections. Ce ne serait pas possible de les utiliser avec les objets pour déterminer quel kart (s'il y en a un) s'est connecté ou déconnecté ?

**Comment by ThiraNoe** [comment]
@lj44-ch game_data n'est émis que si la partie est déjà lancée, alors que là j'en ai besoin justement avant que la partie commence...

**Comment by lj44-ch** [comment]
C'était le cas, mais maintenant à chaque connections et déconnections un événement game_data est émis,partie commencée ou non. L'émission lors d'une nouvelle connections lorsque la partie n a pas encore commencé à été mise en commentaires pour éviter que le bouton start soit inaccessible, comme décrit dans l'issue #67.
