### ISSUE TITLE
Le preview des mondes ne se met pas à jour si le monde a été modifié

### ISSUE THREAD

**Issue by lj44-ch** [lj44-ch/kart-simulator#94]
Si le joueur clique sur "Update the worlds now" avec un monde sélectionné et que celui-ci est mis à jour, le preview de ce monde n'est pas mis à jour. Le joueur est obligé de sélectionné un autre monde et à nouveau le monde concerné pour que l'affichage se mette à jour.

**Comment by ThiraNoe** [comment]
Réglé en ajoutant un argument callback à UpdateWorldButton
